name: Build and Deploy

on:
  push:
    # tags: ["v[0-9].[0-9]+.[0-9]+"]
    branches:
      # - "development"
      # - "staging"
      - "main"

jobs:
  provision-packer:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
      AWS_SESSION_TOKEN: ${{ secrets.aws_session_token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Packer
        id: setup
        uses: hashicorp/setup-packer@main

      - name: Initialize Packer
        id: initpacker
        run: packer init ubuntu24

      - name: Format Packer
        id: fmtpacker
        run: packer fmt ubuntu24

      - name: Validate Packer
        id: validate
        run: packer validate ubuntu24

      - name: Build Image
        id: build
        run: packer build ubuntu24